import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowLeft, Check, Clock3, Dumbbell, Footprints, Leaf, Pause, Play, X } from 'lucide-react';
import { today } from './data';
const categoryIcon = { Strength: Dumbbell, Cardio: Footprints, Mobility: Leaf };
export function Icon({ category, size = 20 }) { const Component = categoryIcon[category] || Activity; return <Component size={size} />; }
export function Progress({ value, goal, className = '' }) { return <div className={`progress ${className}`} role="progressbar" aria-label="Goal progress" aria-valuenow={Math.round(Math.min(value / Math.max(goal, 1) * 100, 100))} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${Math.min(value / Math.max(goal, 1) * 100, 100)}%` }} /></div>; }
export function PanelTitle({ title, children }) { return <div className="panel-title"><h2>{title}</h2>{children}</div>; }
export function Empty({ title, text }) { return <div className="empty"><Activity size={28} /><h3>{title}</h3><p>{text}</p></div>; }
export function Modal({ title, children, close }) {
  const ref = useRef(null);
  useEffect(() => { const dialog = ref.current; dialog.showModal(); const prev = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = prev; }; }, []);
  return <dialog ref={ref} className="modal" aria-labelledby="modal-title" onCancel={e => { e.preventDefault(); close(); }} onClick={e => { if (e.target === ref.current) close(); }}><div className="modal-heading"><h2 id="modal-title">{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={close}><X size={20} /></button></div>{children}</dialog>;
}
export function Field({ label, ...props }) { return <label className="field"><span>{label}</span><input {...props} /></label>; }
function Select({ label, children, ...props }) { return <label className="field"><span>{label}</span><select {...props}>{children}</select></label>; }
export function EntryForm({ type, initial = {}, onSubmit, busy }) {
  const isMeal = type === 'meal', custom = type === 'custom';
  function submit(e) { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); for (const key of ['durationMinutes','calories','protein','carbs','fat','steps']) if (key in f) f[key] = Number(f[key]); if (custom) f.exercises = f.exercises.split('\n').map(s=>s.trim()).filter(Boolean); onSubmit(f); }
  return <form onSubmit={submit} className="entry-form">{type === 'steps' ? <><p className="modal-copy">Enter your total for today. This replaces your previous step count.</p><Field label="Total steps" name="steps" type="number" min="0" max="200000" defaultValue={initial.steps || 0} required /></> : <><Field label={isMeal ? 'What did you eat?' : 'Workout name'} name={isMeal ? 'name' : 'title'} placeholder={isMeal ? 'e.g. Rice bowl with vegetables' : 'e.g. Evening walk'} defaultValue={initial.title} required maxLength={100} /><div className="form-grid"><Select label={isMeal ? 'Meal' : 'Category'} name={isMeal ? 'type' : 'category'} defaultValue={initial.type || initial.category}>{(isMeal ? ['Breakfast','Lunch','Dinner','Snack'] : ['Strength','Cardio','Mobility']).map(v=><option key={v}>{v}</option>)}</Select>{!custom && <Field label="Date" name="date" type="date" defaultValue={initial.date || today()} max={today()} required />}{!isMeal && <Field label="Duration (minutes)" name="durationMinutes" type="number" min="1" max="1440" defaultValue={initial.durationMinutes || ''} required />}{!custom && <Field label={isMeal ? 'Calories (kcal)' : 'Activity calories (kcal)'} name="calories" type="number" min="0" max="15000" defaultValue={isMeal ? '' : 0} required />}{isMeal && ['protein','carbs','fat'].map(key=><Field key={key} label={`${key[0].toUpperCase()+key.slice(1)} (g, optional)`} name={key} type="number" step="0.1" min="0" max="2000" />)}</div>{custom && <label className="field"><span>Exercises (one per line)</span><textarea name="exercises" rows="5" defaultValue={Array.isArray(initial.exercises) ? initial.exercises.map(e => typeof e === 'string' ? e : e.name).join('\n') : initial.exercises || ''} maxLength={2000} placeholder={'Warm-up · 5 minutes\nSquat · 3 × 10'} required /></label>}</>}<div className="modal-actions"><button type="submit" className="button primary" disabled={busy}><Check size={17} />{busy ? 'Saving…' : custom ? 'Create workout' : 'Save entry'}</button></div></form>;
}
export function WorkoutSession({ plan, busy, onComplete }) {
  const [running, setRunning] = useState(false), [elapsed, setElapsed] = useState(0), [started, setStarted] = useState(false), [finish, setFinish] = useState(false);
  const [checked, setChecked] = useState([]);
  const startedAt = useRef(0), accumulated = useRef(0);
  useEffect(() => { if (!running) return; const t = setInterval(() => setElapsed(accumulated.current + Math.floor((Date.now() - startedAt.current) / 1000)), 250); return () => clearInterval(t); }, [running]);
  function toggle() { if (running) { accumulated.current += Math.floor((Date.now() - startedAt.current) / 1000); setElapsed(accumulated.current); } else { startedAt.current = Date.now(); setStarted(true); } setRunning(!running); }
  const exercises = Array.isArray(plan.exercises) ? plan.exercises : String(plan.exercises || '').split(',');
  if (finish) return <><p className="modal-copy">Review your completed session. Enter your actual duration and activity calories before saving.</p><EntryForm type="workout" busy={busy} initial={{ title: plan.title, category: plan.category, durationMinutes: Math.max(1, Math.round(elapsed / 60)) }} onSubmit={onComplete} /><button className="text-link" onClick={()=>setFinish(false)}><ArrowLeft size={15} />Back to session</button></>;
  return <><div className="session-meta"><span className="status-pill">{plan.category}</span><span><Clock3 size={16} />{plan.durationMinutes || parseInt(plan.duration) || 30} min planned</span></div><p className="modal-copy">{plan.equipment || 'Your own equipment'}</p><div className="exercise-checklist">{exercises.map((e,i)=><label key={i}><input type="checkbox" checked={checked.includes(i)} onChange={()=>setChecked(c=>c.includes(i)?c.filter(n=>n!==i):[...c,i])} /><span>{typeof e === 'string' ? e : `${e.name} ${e.sets || ''} ${e.reps || ''}`}</span></label>)}</div><div className="session-timer"><span>{String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</span><small>{checked.length} of {exercises.length} exercises checked</small></div><div className="modal-actions"><button className="button secondary" onClick={toggle}>{running ? <Pause size={17} /> : <Play size={17} />}{running ? 'Pause' : started ? 'Resume' : 'Start session'}</button><button className="button primary" disabled={!started} onClick={()=>{ if(running) toggle(); setFinish(true); }}>Finish & review<Check size={17} /></button></div></>;
}

