// Food catalog, values per 100 g. Sources: USDA FoodData Central (fdcId), USDA SR Legacy, IFCT 2017 (Indian dishes, approximate).
// units = grams per household measure, unit = default measure for a bare count.
const f = (id, name, aliases, calories, protein, carbs, fat, units, unit, source, fdcId) =>
  ({ id, name, aliases, calories, protein, carbs, fat, units, unit, source, ...(fdcId ? { fdcId } : {}) });

export default [
  // --- Breads and breakfast staples ---
  f('roti', 'Roti / chapati, whole wheat, no oil', ['roti', 'chapati', 'chapathi', 'phulka', 'rotis', 'chapatis'], 265, 9, 52, 3.5, { piece: 40, small: 30, medium: 40, large: 55 }, 'piece', 'IFCT'),
  f('paratha', 'Paratha, plain, with oil', ['paratha', 'plain paratha', 'parantha'], 320, 7, 42, 13, { piece: 80, small: 60, medium: 80, large: 100 }, 'piece', 'IFCT'),
  f('aloo-paratha', 'Aloo paratha (potato stuffed)', ['aloo paratha', 'potato paratha', 'stuffed paratha'], 260, 5, 35, 10, { piece: 100 }, 'piece', 'IFCT'),
  f('naan', 'Naan', ['naan', 'butter naan', 'plain naan'], 300, 9, 50, 7, { piece: 90 }, 'piece', 'IFCT'),
  f('puri', 'Puri, fried', ['puri', 'poori', 'puris'], 400, 6, 45, 22, { piece: 30 }, 'piece', 'IFCT'),
  f('white-bread', 'Bread, white, slice', ['white bread', 'bread', 'bread slice', 'toast', 'white toast'], 265, 9, 49, 3.2, { slice: 28, piece: 28 }, 'slice', 'USDA SR'),
  f('brown-bread', 'Bread, whole wheat / brown, slice', ['brown bread', 'whole wheat bread', 'wheat bread', 'multigrain bread', 'brown toast'], 250, 12, 42, 3.5, { slice: 30, piece: 30 }, 'slice', 'USDA SR'),
  f('idli', 'Idli, steamed', ['idli', 'idly', 'idlis'], 130, 4, 26, 0.5, { piece: 40 }, 'piece', 'IFCT'),
  f('dosa', 'Dosa, plain', ['dosa', 'plain dosa', 'dosai', 'sada dosa'], 170, 4, 28, 4, { piece: 80 }, 'piece', 'IFCT'),
  f('masala-dosa', 'Masala dosa', ['masala dosa', 'masala dosai'], 200, 4, 28, 7, { piece: 180 }, 'piece', 'IFCT'),
  f('uttapam', 'Uttapam', ['uttapam', 'uthappam', 'onion uttapam'], 180, 5, 28, 5, { piece: 120 }, 'piece', 'IFCT'),
  f('upma', 'Upma (semolina)', ['upma', 'rava upma', 'sooji upma'], 150, 3.5, 25, 4, { katori: 150, bowl: 200, cup: 150, plate: 250 }, 'katori', 'IFCT'),
  f('poha', 'Poha (flattened rice, cooked)', ['poha', 'kanda poha', 'aval', 'pohe'], 160, 3, 28, 4, { katori: 150, bowl: 200, cup: 150, plate: 250 }, 'bowl', 'IFCT'),
  f('oats', 'Oats, whole grain, rolled, dry', ['oats', 'oat', 'rolled oats', 'dry oats', 'raw oats'], 379, 13.5, 68.7, 5.89, { cup: 80, tbsp: 10, bowl: 40, scoop: 40 }, 'bowl', 'USDA', 2346396),
  f('oats-porridge', 'Oats porridge, cooked with milk', ['oats porridge', 'porridge', 'oatmeal', 'cooked oats', 'oats with milk', 'masala oats'], 100, 4, 15, 3, { bowl: 250, katori: 150, cup: 240 }, 'bowl', 'IFCT'),
  f('cornflakes', 'Cornflakes, dry', ['cornflakes', 'corn flakes', 'cereal'], 357, 7, 84, 0.4, { cup: 30, bowl: 40 }, 'bowl', 'USDA SR'),
  f('muesli', 'Muesli, dry', ['muesli', 'granola'], 360, 10, 66, 6, { cup: 85, bowl: 60, handful: 30 }, 'bowl', 'USDA SR'),
  // --- Rice and grains ---
  f('rice', 'Rice, white, cooked', ['rice', 'white rice', 'cooked rice', 'steamed rice', 'boiled rice', 'plain rice', 'chawal', 'basmati rice'], 130, 2.7, 28, 0.3, { cup: 160, katori: 150, bowl: 200, plate: 250, tbsp: 15, scoop: 60 }, 'katori', 'USDA SR'),
  f('raw-rice', 'Rice, white, long grain, raw', ['raw rice', 'uncooked white rice', 'raw white rice', 'uncooked rice'], 370, 7.04, 80.3, 1.03, { cup: 185, tbsp: 12 }, 'cup', 'USDA', 2512381),
  f('brown-rice', 'Rice, brown, cooked', ['brown rice', 'cooked brown rice'], 123, 2.7, 26, 1, { cup: 160, katori: 150, bowl: 200, plate: 250 }, 'katori', 'USDA SR'),
  f('jeera-rice', 'Jeera rice', ['jeera rice', 'cumin rice', 'ghee rice'], 160, 3, 28, 4, { cup: 160, katori: 150, bowl: 200, plate: 250 }, 'katori', 'IFCT'),
  f('pulao', 'Vegetable pulao', ['pulao', 'veg pulao', 'vegetable pulao', 'pilaf', 'pulav'], 150, 3.5, 25, 4.5, { cup: 160, katori: 150, bowl: 200, plate: 250 }, 'plate', 'IFCT'),
  f('chicken-biryani', 'Chicken biryani', ['chicken biryani', 'biryani', 'biriyani'], 180, 9, 22, 6, { cup: 160, katori: 150, bowl: 200, plate: 300 }, 'plate', 'IFCT'),
  f('veg-biryani', 'Vegetable biryani', ['veg biryani', 'vegetable biryani'], 160, 4, 25, 5, { cup: 160, katori: 150, bowl: 200, plate: 300 }, 'plate', 'IFCT'),
  f('khichdi', 'Khichdi (rice and dal)', ['khichdi', 'kichdi', 'khichri', 'pongal'], 120, 4.5, 20, 2.5, { bowl: 200, katori: 150, plate: 250 }, 'bowl', 'IFCT'),
  f('curd-rice', 'Curd rice', ['curd rice', 'thayir sadam', 'dahi chawal'], 130, 4, 20, 3.5, { bowl: 200, katori: 150, plate: 250 }, 'bowl', 'IFCT'),
  f('fried-rice', 'Fried rice (vegetable)', ['fried rice', 'veg fried rice', 'egg fried rice'], 165, 4, 26, 5, { plate: 250, bowl: 200, cup: 160 }, 'plate', 'IFCT'),
  f('noodles', 'Noodles / chowmein, vegetable', ['noodles', 'chowmein', 'chow mein', 'hakka noodles', 'veg noodles'], 180, 5, 28, 6, { plate: 250, bowl: 200, cup: 160 }, 'plate', 'IFCT'),
  f('instant-noodles', 'Instant noodles, cooked (masala)', ['instant noodles', 'maggi', 'maggie', 'cup noodles'], 140, 3, 18, 6, { pack: 300, packet: 300, bowl: 250, cup: 200 }, 'pack', 'IFCT'),
  f('pasta', 'Pasta, cooked, with sauce', ['pasta', 'spaghetti', 'macaroni', 'penne', 'red sauce pasta', 'white sauce pasta'], 158, 5.8, 31, 0.9, { plate: 250, bowl: 200, cup: 140 }, 'plate', 'USDA SR'),
  f('quinoa', 'Quinoa, cooked', ['quinoa', 'cooked quinoa'], 120, 4.4, 21, 1.9, { cup: 185, bowl: 200, katori: 150 }, 'cup', 'USDA SR'),
  // --- Dal and legumes ---
  f('dal', 'Dal, cooked (toor / mixed)', ['dal', 'daal', 'dhal', 'toor dal', 'arhar dal', 'dal tadka', 'dal fry', 'yellow dal', 'masoor dal', 'urad dal'], 100, 6, 15, 2, { katori: 150, bowl: 200, cup: 240, tbsp: 15 }, 'katori', 'IFCT'),
  f('moong-dal', 'Moong dal, cooked', ['moong dal', 'mung dal', 'green gram dal', 'moong'], 105, 7, 16, 1.5, { katori: 150, bowl: 200, cup: 240 }, 'katori', 'IFCT'),
  f('dal-makhani', 'Dal makhani', ['dal makhani', 'dal makhni', 'makhani dal'], 160, 7, 17, 7, { katori: 150, bowl: 200, cup: 240 }, 'katori', 'IFCT'),
  f('sambar', 'Sambar', ['sambar', 'sambhar'], 60, 3, 9, 1.5, { katori: 150, bowl: 200, cup: 240 }, 'katori', 'IFCT'),
  f('rasam', 'Rasam', ['rasam'], 30, 1, 5, 0.5, { katori: 150, bowl: 200, cup: 240 }, 'katori', 'IFCT'),
  f('chole', 'Chole / chana masala', ['chole', 'chhole', 'chana masala', 'chana', 'chickpea curry', 'channa'], 150, 7, 20, 5, { katori: 150, bowl: 200, cup: 240 }, 'katori', 'IFCT'),
  f('egg-curry', 'Egg curry', ['egg curry', 'anda curry', 'egg masala'], 150, 9, 5, 10, { katori: 150, bowl: 200, piece: 90 }, 'katori', 'IFCT'),
  f('bhatura', 'Bhatura, fried', ['bhatura', 'bhature', 'bhatoora'], 330, 7, 45, 14, { piece: 90 }, 'piece', 'IFCT'),
  f('rajma', 'Rajma (kidney bean curry)', ['rajma', 'rajmah', 'kidney beans curry', 'kidney beans'], 130, 7, 20, 3, { katori: 150, bowl: 200, cup: 240 }, 'katori', 'IFCT'),
  f('chickpeas', 'Chickpeas, canned, drained', ['canned chickpeas', 'drained chickpeas', 'boiled chickpeas', 'chickpeas', 'kabuli chana'], 133, 7.02, 20.3, 3.1, { cup: 160, katori: 150, handful: 40 }, 'cup', 'USDA', 2644288),
  f('lentils', 'Lentils, boiled', ['lentils', 'boiled lentils', 'cooked lentils'], 116, 9, 20, 0.4, { cup: 200, katori: 150 }, 'cup', 'USDA SR'),
  f('sprouts', 'Moong sprouts', ['sprouts', 'moong sprouts', 'sprouted moong', 'bean sprouts'], 95, 7, 14, 0.5, { cup: 100, katori: 100, bowl: 150, handful: 40 }, 'katori', 'IFCT'),
  f('hummus', 'Hummus, commercial', ['hummus', 'humus'], 229, 7.35, 14.9, 17.1, { tbsp: 15, cup: 240 }, 'tbsp', 'USDA', 321358),
  // --- Vegetables and sabzi ---
  f('sabzi', 'Mixed vegetable sabzi', ['sabzi', 'sabji', 'subzi', 'mixed veg', 'mix veg', 'vegetable curry', 'veg curry', 'mixed vegetables', 'curry'], 90, 2.5, 10, 4.5, { katori: 120, bowl: 180, cup: 150, tbsp: 15 }, 'katori', 'IFCT'),
  f('aloo-sabzi', 'Aloo (potato) sabzi', ['aloo sabzi', 'aloo', 'potato sabzi', 'aloo gobi', 'aloo matar', 'jeera aloo', 'dum aloo'], 120, 2, 18, 5, { katori: 120, bowl: 180, cup: 150 }, 'katori', 'IFCT'),
  f('bhindi', 'Bhindi (okra) sabzi', ['bhindi', 'okra', 'bhindi masala', 'ladies finger'], 90, 2, 8, 6, { katori: 120, bowl: 180, cup: 150 }, 'katori', 'IFCT'),
  f('baingan', 'Baingan (brinjal) sabzi / bharta', ['baingan', 'brinjal', 'baingan bharta', 'eggplant', 'aubergine'], 90, 2, 8, 6, { katori: 120, bowl: 180, cup: 150 }, 'katori', 'IFCT'),
  f('gobi', 'Gobi (cauliflower) sabzi', ['gobi', 'gobhi', 'cauliflower', 'cauliflower sabzi', 'gobi masala'], 80, 2.5, 8, 4.5, { katori: 120, bowl: 180, cup: 150 }, 'katori', 'IFCT'),
  f('palak-paneer', 'Palak paneer', ['palak paneer', 'saag paneer', 'spinach paneer'], 180, 9, 8, 13, { katori: 150, bowl: 200, cup: 240 }, 'katori', 'IFCT'),
  f('paneer-butter-masala', 'Paneer butter masala', ['paneer butter masala', 'paneer masala', 'shahi paneer', 'kadai paneer', 'paneer curry', 'paneer tikka masala', 'matar paneer'], 250, 10, 10, 20, { katori: 150, bowl: 200, cup: 240 }, 'katori', 'IFCT'),
  f('spinach', 'Spinach, cooked', ['spinach', 'palak', 'cooked spinach', 'saag'], 23, 3, 3.8, 0.3, { cup: 180, katori: 120 }, 'katori', 'USDA SR'),
  f('broccoli', 'Broccoli, raw', ['raw broccoli', 'broccoli'], 31, 2.57, 6.27, 0.34, { cup: 90, piece: 150, katori: 100 }, 'cup', 'USDA', 747447),
  f('salad', 'Green salad (no dressing)', ['salad', 'green salad', 'garden salad', 'kachumber', 'mixed salad'], 20, 1, 4, 0.2, { bowl: 100, plate: 150, cup: 80, katori: 80 }, 'bowl', 'USDA SR'),
  f('cucumber', 'Cucumber, raw', ['cucumber', 'kheera', 'kakdi'], 15, 0.7, 3.6, 0.1, { piece: 200, slice: 7, cup: 120 }, 'piece', 'USDA SR'),
  f('tomato', 'Tomato, raw', ['tomato', 'tomatoes', 'tamatar'], 18, 0.9, 3.9, 0.2, { piece: 120, slice: 20, cup: 180 }, 'piece', 'USDA SR'),
  f('grape-tomato', 'Tomatoes, grape, raw', ['grape tomatoes', 'cherry tomatoes'], 27, 0.83, 5.51, 0.63, { piece: 8, cup: 150, handful: 60 }, 'cup', 'USDA', 321360),
  f('onion', 'Onion, raw', ['onion', 'onions', 'pyaz'], 40, 1.1, 9.3, 0.1, { piece: 110, slice: 14, cup: 160 }, 'piece', 'USDA SR'),
  f('carrot', 'Carrot, raw', ['carrot', 'carrots', 'gajar'], 41, 0.9, 10, 0.2, { piece: 60, cup: 128 }, 'piece', 'USDA SR'),
  f('potato', 'Potato, boiled', ['potato', 'boiled potato', 'potatoes', 'boiled potatoes'], 87, 1.9, 20, 0.1, { piece: 150, small: 100, medium: 150, large: 250, cup: 160 }, 'piece', 'USDA SR'),
  f('sweet-potato', 'Sweet potato, boiled', ['sweet potato', 'shakarkandi', 'boiled sweet potato'], 86, 1.6, 20, 0.1, { piece: 130, cup: 200 }, 'piece', 'USDA SR'),
  f('corn', 'Sweet corn, boiled', ['corn', 'sweet corn', 'corn kernels', 'bhutta'], 96, 3.4, 21, 1.5, { cup: 165, piece: 100, katori: 120 }, 'cup', 'USDA SR'),
  // --- Eggs, paneer, meat and fish ---
  f('egg', 'Egg, whole, boiled', ['egg', 'eggs', 'boiled egg', 'boiled eggs', 'hard boiled egg', 'anda'], 155, 13, 1.1, 11, { piece: 50, small: 42, medium: 50, large: 56 }, 'piece', 'USDA SR'),
  f('raw-egg', 'Eggs, Grade A, large, whole, raw', ['raw egg', 'raw eggs'], 148, 12.4, 0.96, 9.96, { piece: 50 }, 'piece', 'USDA', 748967),
  f('egg-white', 'Egg white, boiled', ['egg white', 'egg whites', 'boiled egg white'], 52, 11, 0.7, 0.2, { piece: 33 }, 'piece', 'USDA SR'),
  f('omelette', 'Omelette, 2 eggs, with oil', ['omelette', 'omelet', 'egg omelette', 'masala omelette', 'cheese omelette'], 190, 12, 1.5, 15, { piece: 110, small: 60, medium: 110, large: 170 }, 'piece', 'IFCT'),
  f('egg-bhurji', 'Egg bhurji (scrambled, spiced)', ['egg bhurji', 'anda bhurji', 'scrambled eggs', 'scrambled egg', 'bhurji'], 180, 12, 3, 13, { katori: 120, plate: 150, piece: 110 }, 'katori', 'IFCT'),
  f('paneer', 'Paneer, raw', ['paneer', 'cottage cheese', 'paneer cubes', 'paneer tikka', 'grilled paneer', 'paneer bhurji'], 265, 18, 6, 20, { cube: 15, piece: 15, cup: 120, katori: 100, slice: 30 }, 'piece', 'IFCT'),
  f('tofu', 'Tofu, firm', ['tofu', 'soya paneer', 'firm tofu'], 76, 8, 2, 4.8, { cube: 15, piece: 15, cup: 120, block: 300 }, 'cup', 'USDA SR'),
  f('chicken-breast', 'Chicken breast, skinless, cooked', ['chicken breast', 'grilled chicken', 'grilled chicken breast', 'cooked chicken breast', 'braised chicken breast', 'boiled chicken', 'chicken'], 166, 32.1, 0, 3.24, { piece: 120, small: 90, medium: 120, large: 170, cup: 140 }, 'piece', 'USDA', 331960),
  f('chicken-curry', 'Chicken curry, home style', ['chicken curry', 'chicken masala', 'chicken gravy', 'kadai chicken', 'chicken korma'], 150, 14, 5, 8, { katori: 150, bowl: 200, piece: 80, cup: 240 }, 'katori', 'IFCT'),
  f('butter-chicken', 'Butter chicken', ['butter chicken', 'murgh makhani', 'chicken tikka masala'], 220, 16, 6, 15, { katori: 150, bowl: 200, cup: 240 }, 'katori', 'IFCT'),
  f('tandoori-chicken', 'Tandoori chicken', ['tandoori chicken', 'chicken tikka', 'tandoori', 'chicken kebab', 'roasted chicken'], 200, 25, 3, 10, { piece: 120, leg: 120, plate: 250 }, 'piece', 'IFCT'),
  f('fish-curry', 'Fish curry', ['fish curry', 'fish masala', 'fish gravy', 'machli'], 140, 15, 4, 7, { katori: 150, bowl: 200, piece: 100 }, 'katori', 'IFCT'),
  f('grilled-fish', 'Fish, grilled or steamed', ['grilled fish', 'fish', 'steamed fish', 'baked fish', 'fish fillet', 'salmon', 'tuna'], 130, 22, 0, 4, { piece: 120, fillet: 150, small: 90, medium: 120, large: 170 }, 'piece', 'USDA SR'),
  f('fried-fish', 'Fish fry', ['fish fry', 'fried fish', 'fish fingers'], 230, 18, 10, 13, { piece: 100 }, 'piece', 'IFCT'),
  f('prawns', 'Prawns, cooked', ['prawns', 'prawn', 'shrimp', 'prawn curry'], 100, 21, 0.5, 1.2, { piece: 10, cup: 140, katori: 120 }, 'katori', 'USDA SR'),
  f('mutton-curry', 'Mutton curry', ['mutton curry', 'mutton', 'lamb curry', 'goat curry', 'mutton masala'], 220, 16, 4, 15, { katori: 150, bowl: 200, piece: 60 }, 'katori', 'IFCT'),
  f('keema', 'Keema (minced meat), cooked', ['keema', 'kheema', 'minced meat', 'mince'], 210, 18, 4, 14, { katori: 150, bowl: 200 }, 'katori', 'IFCT'),
  f('whey', 'Whey protein powder', ['whey', 'whey protein', 'protein powder', 'protein shake powder', 'protein'], 400, 78, 8, 6, { scoop: 30, tbsp: 10 }, 'scoop', 'USDA SR'),
  f('soya-chunks', 'Soya chunks, dry', ['soya chunks', 'soy chunks', 'nutrela', 'soya nuggets', 'soya'], 345, 52, 33, 0.5, { cup: 50, katori: 40, handful: 25 }, 'katori', 'IFCT'),
  // --- Dairy ---
  f('whole-milk', 'Milk, whole, 3.25% fat', ['whole milk', 'full cream milk', 'milk', 'full fat milk'], 60, 3.27, 4.63, 3.2, { glass: 250, cup: 240, ml: 1, tbsp: 15 }, 'glass', 'USDA', 746782),
  f('toned-milk', 'Milk, toned (3% fat)', ['toned milk', 'amul taaza', 'standard milk'], 58, 3.1, 4.7, 3, { glass: 250, cup: 240, ml: 1 }, 'glass', 'IFCT'),
  f('reduced-fat-milk', 'Milk, reduced fat, 2%', ['2% milk', 'reduced fat milk', 'low fat milk', 'double toned milk'], 50, 3.36, 4.9, 1.9, { glass: 250, cup: 240, ml: 1 }, 'glass', 'USDA', 746778),
  f('skim-milk', 'Milk, skimmed', ['skim milk', 'skimmed milk', 'fat free milk'], 35, 3.4, 5, 0.1, { glass: 250, cup: 240, ml: 1 }, 'glass', 'USDA SR'),
  f('curd', 'Curd / dahi, whole milk', ['curd', 'dahi', 'yogurt', 'yoghurt', 'plain yogurt', 'plain curd'], 60, 3.1, 4, 3.3, { katori: 150, bowl: 150, cup: 240, tbsp: 15, glass: 250 }, 'katori', 'IFCT'),
  f('greek-yogurt', 'Yogurt, Greek, plain, nonfat', ['greek yogurt', 'plain nonfat greek yogurt', 'greek yoghurt'], 61, 10.3, 3.64, 0.37, { cup: 240, katori: 150, tbsp: 15, bowl: 150 }, 'cup', 'USDA', 330137),
  f('buttermilk', 'Buttermilk / chaas', ['buttermilk', 'chaas', 'chach', 'chaach', 'mattha'], 40, 2, 4, 1.5, { glass: 250, cup: 240, ml: 1 }, 'glass', 'IFCT'),
  f('lassi', 'Lassi, sweet', ['lassi', 'sweet lassi', 'mango lassi'], 110, 3, 16, 3.5, { glass: 250, cup: 240, ml: 1 }, 'glass', 'IFCT'),
  f('raita', 'Raita', ['raita', 'boondi raita', 'cucumber raita'], 60, 3, 4, 3, { katori: 100, bowl: 150, tbsp: 15 }, 'katori', 'IFCT'),
  f('cheese', 'Cheese, cheddar / processed', ['cheese', 'cheddar', 'cheese slice', 'processed cheese', 'amul cheese'], 400, 25, 1.3, 33, { slice: 20, cube: 20, piece: 20, tbsp: 15, cup: 110 }, 'slice', 'USDA SR'),
  f('butter', 'Butter', ['butter', 'makhan', 'amul butter'], 717, 0.9, 0.1, 81, { tsp: 5, tbsp: 14, cube: 10 }, 'tsp', 'USDA SR'),
  f('ghee', 'Ghee', ['ghee', 'clarified butter', 'desi ghee'], 900, 0, 0, 100, { tsp: 5, tbsp: 14 }, 'tsp', 'IFCT'),
  f('oil', 'Cooking oil', ['oil', 'cooking oil', 'vegetable oil', 'olive oil', 'mustard oil', 'sunflower oil', 'coconut oil'], 884, 0, 0, 100, { tsp: 5, tbsp: 14, ml: 0.92 }, 'tsp', 'USDA SR'),
  f('ice-cream', 'Ice cream, vanilla', ['ice cream', 'icecream', 'vanilla ice cream', 'kulfi'], 207, 3.5, 24, 11, { scoop: 70, cup: 130, bowl: 130, piece: 70 }, 'scoop', 'USDA SR'),
  // --- Drinks ---
  f('chai', 'Chai, with milk and sugar', ['chai', 'tea', 'milk tea', 'masala chai', 'cutting chai', 'tea with milk'], 60, 1.5, 8, 2.2, { cup: 150, glass: 200, ml: 1 }, 'cup', 'IFCT'),
  f('green-tea', 'Green tea / black tea, no sugar', ['green tea', 'black tea', 'herbal tea', 'lemon tea'], 1, 0, 0.2, 0, { cup: 240, glass: 250, ml: 1 }, 'cup', 'USDA SR'),
  f('black-coffee', 'Coffee, black, no sugar', ['black coffee', 'espresso', 'americano'], 2, 0.1, 0, 0, { cup: 240, ml: 1 }, 'cup', 'USDA SR'),
  f('coffee', 'Coffee with milk and sugar', ['coffee', 'milk coffee', 'filter coffee', 'latte', 'cappuccino', 'cold coffee'], 45, 1.5, 5, 1.8, { cup: 200, glass: 250, ml: 1 }, 'cup', 'IFCT'),
  f('orange-juice', 'Orange juice', ['orange juice', 'juice', 'fruit juice', 'apple juice', 'mixed fruit juice'], 45, 0.7, 10, 0.2, { glass: 250, cup: 240, ml: 1 }, 'glass', 'USDA SR'),
  f('cola', 'Cola / soft drink', ['cola', 'coke', 'pepsi', 'soft drink', 'soda', 'thums up', 'sprite'], 42, 0, 10.6, 0, { can: 330, glass: 250, bottle: 500, ml: 1 }, 'glass', 'USDA SR'),
  f('coconut-water', 'Coconut water', ['coconut water', 'nariyal pani', 'tender coconut'], 19, 0.7, 3.7, 0.2, { glass: 250, cup: 240, piece: 300, ml: 1 }, 'glass', 'USDA SR'),
  f('beer', 'Beer, regular', ['beer'], 43, 0.5, 3.6, 0, { glass: 330, can: 330, bottle: 650, pint: 570, ml: 1 }, 'glass', 'USDA SR'),
  // --- Fruit ---
  f('banana', 'Banana, raw', ['banana', 'bananas', 'kela'], 97, 0.74, 23, 0.29, { piece: 118, small: 100, medium: 118, large: 140, cup: 150 }, 'piece', 'USDA', 1105314),
  f('apple', 'Apple, raw', ['apple', 'apples', 'seb'], 52, 0.3, 14, 0.2, { piece: 180, small: 150, medium: 180, large: 220, cup: 125, slice: 20 }, 'piece', 'USDA SR'),
  f('mango', 'Mango, raw', ['mango', 'mangoes', 'aam'], 60, 0.8, 15, 0.4, { piece: 200, cup: 165, slice: 40 }, 'piece', 'USDA SR'),
  f('orange', 'Orange, raw', ['orange', 'oranges', 'santra', 'mosambi'], 47, 0.9, 12, 0.1, { piece: 130, cup: 180 }, 'piece', 'USDA SR'),
  f('papaya', 'Papaya, raw', ['papaya', 'papita'], 43, 0.5, 11, 0.3, { cup: 145, bowl: 200, slice: 100, katori: 120 }, 'bowl', 'USDA SR'),
  f('grapes', 'Grapes, raw', ['grapes', 'grape', 'angoor'], 69, 0.7, 18, 0.2, { cup: 150, handful: 50, katori: 120, bowl: 150 }, 'cup', 'USDA SR'),
  f('watermelon', 'Watermelon, raw', ['watermelon', 'tarbooz'], 30, 0.6, 7.6, 0.2, { cup: 150, bowl: 200, slice: 280, katori: 120 }, 'bowl', 'USDA SR'),
  f('pomegranate', 'Pomegranate arils', ['pomegranate', 'anar'], 83, 1.7, 19, 1.2, { cup: 175, katori: 120, bowl: 150, piece: 280 }, 'katori', 'USDA SR'),
  f('guava', 'Guava, raw', ['guava', 'amrood'], 68, 2.6, 14, 1, { piece: 90 }, 'piece', 'USDA SR'),
  f('pear', 'Pear, raw', ['pear', 'pears'], 57, 0.4, 15, 0.1, { piece: 180 }, 'piece', 'USDA SR'),
  f('berries', 'Mixed berries, raw', ['berries', 'mixed berries', 'strawberries', 'blueberries', 'strawberry', 'blueberry'], 57, 0.7, 14, 0.3, { cup: 150, handful: 50, katori: 120 }, 'cup', 'USDA SR'),
  f('dates', 'Dates, dried', ['dates', 'date', 'khajoor', 'khajur'], 277, 1.8, 75, 0.2, { piece: 8 }, 'piece', 'USDA SR'),
  f('fruit-salad', 'Fruit salad / mixed fruit', ['fruit salad', 'mixed fruit', 'fruits', 'fruit', 'fruit bowl', 'cut fruit'], 55, 0.7, 14, 0.3, { bowl: 200, cup: 150, katori: 120, plate: 250 }, 'bowl', 'USDA SR'),
  // --- Nuts, seeds and spreads ---
  f('almonds', 'Almonds', ['almonds', 'almond', 'badam'], 579, 21, 22, 50, { piece: 1.2, handful: 28, tbsp: 9, cup: 140 }, 'piece', 'USDA SR'),
  f('peanuts', 'Peanuts, roasted', ['peanuts', 'peanut', 'groundnuts', 'moongphali', 'roasted peanuts'], 567, 26, 16, 49, { handful: 28, tbsp: 9, cup: 145, piece: 0.8, katori: 60 }, 'handful', 'USDA SR'),
  f('walnuts', 'Walnuts', ['walnuts', 'walnut', 'akhrot'], 654, 15, 14, 65, { piece: 4, half: 2, handful: 28, tbsp: 8 }, 'piece', 'USDA SR'),
  f('cashews', 'Cashews', ['cashews', 'cashew', 'kaju', 'cashew nuts'], 553, 18, 30, 44, { piece: 1.5, handful: 28, tbsp: 9 }, 'piece', 'USDA SR'),
  f('mixed-nuts', 'Mixed nuts', ['mixed nuts', 'nuts', 'dry fruits', 'trail mix'], 600, 18, 22, 52, { handful: 28, tbsp: 9, cup: 140, katori: 50 }, 'handful', 'USDA SR'),
  f('peanut-butter', 'Peanut butter, creamy', ['peanut butter', 'creamy peanut butter', 'pb'], 589, 24, 22.7, 49.4, { tbsp: 16, tsp: 5 }, 'tbsp', 'USDA', 2262072),
  f('chia', 'Chia seeds', ['chia seeds', 'chia'], 486, 17, 42, 31, { tbsp: 12, tsp: 4 }, 'tbsp', 'USDA SR'),
  f('flax', 'Flax seeds', ['flax seeds', 'flaxseed', 'alsi'], 534, 18, 29, 42, { tbsp: 10, tsp: 3.5 }, 'tbsp', 'USDA SR'),
  // --- Snacks, street food and fast food ---
  f('samosa', 'Samosa', ['samosa', 'samosas'], 260, 4, 30, 14, { piece: 100, small: 60, medium: 100, large: 130 }, 'piece', 'IFCT'),
  f('pakora', 'Pakora / bhajiya', ['pakora', 'pakoda', 'bhajiya', 'bhaji', 'onion pakora', 'pakoras'], 300, 6, 28, 18, { piece: 30, plate: 150 }, 'piece', 'IFCT'),
  f('vada-pav', 'Vada pav', ['vada pav', 'wada pav', 'vada'], 290, 6, 42, 11, { piece: 130 }, 'piece', 'IFCT'),
  f('pav-bhaji', 'Pav bhaji', ['pav bhaji', 'pav bhaaji'], 150, 4, 22, 5, { plate: 300, bowl: 250 }, 'plate', 'IFCT'),
  f('dhokla', 'Dhokla', ['dhokla', 'khaman', 'khaman dhokla'], 160, 6, 25, 4, { piece: 40, plate: 160 }, 'piece', 'IFCT'),
  f('bhel', 'Bhel puri / chaat', ['bhel', 'bhel puri', 'chaat', 'sev puri', 'papdi chaat'], 190, 5, 30, 6, { plate: 150, bowl: 150, cup: 120 }, 'plate', 'IFCT'),
  f('khakhra', 'Khakhra', ['khakhra', 'khakra'], 380, 10, 60, 10, { piece: 15 }, 'piece', 'IFCT'),
  f('murukku', 'Murukku / chakli', ['murukku', 'chakli', 'chakri'], 500, 8, 55, 28, { piece: 15, handful: 30 }, 'piece', 'IFCT'),
  f('namkeen', 'Namkeen / mixture', ['namkeen', 'mixture', 'chivda', 'bhujia', 'haldiram'], 520, 10, 50, 32, { handful: 30, katori: 50, pack: 40, tbsp: 10 }, 'handful', 'IFCT'),
  f('papad', 'Papad, roasted', ['papad', 'papadum', 'appalam'], 370, 25, 55, 2, { piece: 10 }, 'piece', 'IFCT'),
  f('biscuits', 'Biscuits (Marie / glucose)', ['biscuit', 'biscuits', 'marie', 'parle g', 'parle-g', 'cookies', 'cookie', 'digestive'], 450, 7, 75, 13, { piece: 8, pack: 60 }, 'piece', 'IFCT'),
  f('chips', 'Potato chips', ['chips', 'potato chips', 'lays', 'wafers', 'crisps'], 536, 7, 53, 35, { handful: 28, pack: 30, packet: 30, small: 30, large: 52 }, 'pack', 'USDA SR'),
  f('chocolate', 'Chocolate, milk', ['chocolate', 'dairy milk', 'milk chocolate', 'kitkat', 'chocolate bar'], 546, 5, 60, 31, { bar: 40, piece: 10, small: 13, square: 6 }, 'bar', 'USDA SR'),
  f('cake', 'Cake, sponge with icing', ['cake', 'pastry', 'cupcake', 'brownie', 'muffin'], 350, 4, 50, 15, { slice: 80, piece: 80 }, 'slice', 'USDA SR'),
  f('gulab-jamun', 'Gulab jamun', ['gulab jamun', 'gulab jamoon'], 300, 4, 45, 12, { piece: 40 }, 'piece', 'IFCT'),
  f('jalebi', 'Jalebi', ['jalebi', 'jilebi'], 350, 2, 55, 14, { piece: 30 }, 'piece', 'IFCT'),
  f('laddu', 'Laddu (besan / boondi)', ['laddu', 'ladoo', 'laddoo', 'besan laddu', 'motichoor laddu'], 400, 8, 55, 18, { piece: 40 }, 'piece', 'IFCT'),
  f('kheer', 'Kheer / payasam', ['kheer', 'payasam', 'rice kheer', 'sheer'], 130, 3.5, 20, 4, { katori: 150, bowl: 200, cup: 240 }, 'katori', 'IFCT'),
  f('halwa', 'Halwa (sooji / gajar)', ['halwa', 'sooji halwa', 'gajar halwa', 'carrot halwa', 'suji halwa'], 300, 4, 40, 14, { katori: 120, bowl: 150, tbsp: 20 }, 'katori', 'IFCT'),
  f('rasgulla', 'Rasgulla', ['rasgulla', 'rasagulla', 'rasmalai'], 190, 4, 35, 3, { piece: 50 }, 'piece', 'IFCT'),
  f('veg-sandwich', 'Vegetable sandwich', ['veg sandwich', 'sandwich', 'vegetable sandwich', 'club sandwich'], 220, 7, 32, 7, { piece: 150, half: 75 }, 'piece', 'IFCT'),
  f('grilled-sandwich', 'Grilled cheese sandwich', ['grilled sandwich', 'cheese sandwich', 'grilled cheese sandwich', 'cheese toast', 'toastie'], 330, 12, 30, 18, { piece: 140, half: 70 }, 'piece', 'USDA SR'),
  f('pizza', 'Pizza, cheese', ['pizza', 'cheese pizza', 'margherita', 'veg pizza'], 266, 11, 33, 10, { slice: 100, piece: 100, small: 300, medium: 600, large: 900 }, 'slice', 'USDA SR'),
  f('veg-burger', 'Burger, vegetable', ['veg burger', 'burger', 'aloo tikki burger', 'mcaloo tikki'], 250, 7, 33, 10, { piece: 200 }, 'piece', 'USDA SR'),
  f('chicken-burger', 'Burger, chicken', ['chicken burger', 'mcchicken', 'zinger'], 260, 13, 28, 11, { piece: 220 }, 'piece', 'USDA SR'),
  f('fries', 'French fries', ['fries', 'french fries', 'finger chips'], 312, 3.4, 41, 15, { serving: 120, handful: 40, small: 80, medium: 120, large: 160, plate: 150 }, 'serving', 'USDA SR'),
  f('momos', 'Momos, vegetable, steamed', ['momos', 'momo', 'veg momos', 'dumplings', 'dim sum'], 180, 6, 28, 5, { piece: 30, plate: 240 }, 'piece', 'IFCT'),
  f('chicken-momos', 'Momos, chicken, steamed', ['chicken momos', 'chicken momo', 'chicken dumplings'], 200, 10, 24, 7, { piece: 30, plate: 240 }, 'piece', 'IFCT'),
  f('spring-roll', 'Spring roll, fried', ['spring roll', 'spring rolls', 'veg spring roll'], 250, 5, 30, 12, { piece: 60 }, 'piece', 'IFCT'),
  f('protein-bar', 'Protein bar', ['protein bar', 'energy bar', 'granola bar'], 380, 25, 40, 12, { bar: 60, piece: 60 }, 'bar', 'USDA SR'),
  // --- Sweeteners, condiments and extras ---
  f('sugar', 'Sugar, granulated', ['sugar', 'granulated sugar', 'cheeni', 'chini'], 385, 0, 99.6, 0.32, { tsp: 4, tbsp: 12, cube: 4, spoon: 4 }, 'tsp', 'USDA', 746784),
  f('honey', 'Honey', ['honey', 'shahad'], 304, 0.3, 82, 0, { tsp: 7, tbsp: 21 }, 'tsp', 'USDA SR'),
  f('jaggery', 'Jaggery', ['jaggery', 'gur', 'gud'], 383, 0.4, 98, 0.1, { piece: 10, tsp: 5, tbsp: 15 }, 'piece', 'IFCT'),
  f('pickle', 'Pickle / achar', ['pickle', 'achar', 'aachar', 'mango pickle'], 60, 1, 6, 4, { tsp: 5, tbsp: 15 }, 'tsp', 'IFCT'),
  f('coconut-chutney', 'Coconut chutney', ['coconut chutney', 'chutney'], 150, 3, 8, 12, { tbsp: 15, katori: 60 }, 'tbsp', 'IFCT'),
  f('green-chutney', 'Green (mint-coriander) chutney', ['green chutney', 'mint chutney', 'hari chutney', 'coriander chutney'], 40, 2, 6, 1, { tbsp: 15, tsp: 5 }, 'tbsp', 'IFCT'),
  f('ketchup', 'Tomato ketchup', ['ketchup', 'tomato ketchup', 'sauce', 'tomato sauce'], 100, 1.2, 25, 0.1, { tbsp: 17, tsp: 6, sachet: 10 }, 'tbsp', 'USDA SR'),
  f('mayonnaise', 'Mayonnaise', ['mayonnaise', 'mayo'], 680, 1, 1, 75, { tbsp: 14, tsp: 5 }, 'tbsp', 'USDA SR'),
  f('jam', 'Jam / fruit preserve', ['jam', 'mixed fruit jam', 'marmalade'], 250, 0.4, 65, 0.1, { tsp: 7, tbsp: 20 }, 'tbsp', 'USDA SR'),
  f('coconut', 'Coconut, fresh', ['coconut', 'fresh coconut', 'grated coconut', 'nariyal'], 354, 3.3, 15, 33, { tbsp: 8, cup: 80, piece: 45 }, 'tbsp', 'USDA SR'),
];
